name = "gitdiagram"
main = "readme.ts"
compatibility_date = "2025-02-19"

dev.port = 3000

# KV for storing diagram results
kv_namespaces = [
  { binding = "DIAGRAMS_KV", id = "0dbeed1b8fe142ddb8df68fb96240710" }
]

assets.directory = "./public"

route = {custom_domain = true, pattern = "diagram.forgithub.com" }

[[queues.producers]]
queue = "diagram-generation-queue"
binding = "DIAGRAM_QUEUE"


[[queues.consumers]]
queue = "diagram-generation-queue"
max_batch_size = 1
max_batch_timeout = 30
max_retries = 3
dead_letter_queue = "diagram-failed-jobs"
